version: "2"

services:
  server:
    image: gitea/gitea:1.16.9-rootless
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_PATH=indexers/repos.bleve
      - GITEA__indexer__UPDATE_BUFFER_LEN=20
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__MAILER_TYPE=smtp
      - GITEA__mailer__IS_TLS_ENABLED=${GITEA__mailer__IS_TLS_ENABLED:-true}
      - GITEA__mailer__FROM=${GITEA__mailer__FROM:-GITEA__mailer__FROM not set}
      - GITEA__mailer__HOST=${GITEA__mailer__HOST:-GITEA__mailer__HOST not set}
      - GITEA__mailer__USER=${GITEA__mailer__USER:-GITEA__mailer__USER not set}
      - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:-GITEA__mailer__PASSWD not set}"""
    restart: unless-stopped
    volumes:
      - ${DATA_SAVE_PATH:-./data/gitea/data}:/var/lib/gitea
      - ${DATA_SAVE_PATH:-./data/config}:/etc/gitea
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${GITEA__database__PASSWD}
      - MYSQL_DATABASE=gitea
    volumes:
      - ${DATA_SAVE_PATH:-./tmp/gitea_mysql}/mysql:/var/lib/mysql
