version: "2"

services:
  server:
    image: gitea/gitea:1.16.9-rootless
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_MYSQL_PASSWORD}
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_PATH=indexers/repos.bleve
      - GITEA__indexer__UPDATE_BUFFER_LEN=20
    restart: unless-stopped
    volumes:
      - ${GITEA_DATA_SAVE_PATH:-./data/gitea/data}:/var/lib/gitea
      - ${GITEA_DATA_SAVE_PATH:-./data/config}:/etc/gitea
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${GITEA_MYSQL_PASSWORD}
      - MYSQL_DATABASE=gitea
    volumes:
      - ${GITEA_DATA_SAVE_PATH:-./tmp/gitea_mysql}/mysql:/var/lib/mysql
